### ISSUE TITLE
Python 中的 * 号以及如何使用它们

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#105]
1.原文链接：[Asterisks in Python: what they are and how to use them](http://treyhunner.com/2018/10/asterisks-in-python-what-they-are-and-how-to-use-them/)
2.分类（见标签）：
3.推荐原因：归纳总结了Python中的*号的各类用途

-------

**Comment by Nana-Lv** [comment]
认领翻译@hanxiaomax

**Comment by hanxiaomax** [comment]
好滴～

**Comment by hanxiaomax** [comment]
@Nana-Lv 注意文章名创建的时候，后缀要是.md，否则校对的时候不能预览。
[参考](https://github.com/jobbole/translation-project/wiki/%E7%BF%BB%E8%AF%91%E6%B5%81%E7%A8%8B#32-%E7%BF%BB%E8%AF%91%E4%B8%ADb2-in-progress)
