### ISSUE TITLE
Understanding Compilers — For Humans

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#11]
1. [原文链接](https://medium.com/@CanHasCommunism/understanding-compilers-for-humans-ba970e045877)
2. 分类：知识普及
3. 推荐原因：详细解释了编译器相关的各种概念，列举了学习资源

-----

原文需要梯子

**Comment by kele1997** [comment]
认领翻译 @hanxiaomax 
ps:作者写了这篇文章的[更新版](https://towardsdatascience.com/understanding-compilers-for-humans-version-2-157f0edb02dd)
