### ISSUE TITLE
学会这两件事，让你成为 Git 专家

### ISSUE THREAD

**Issue by liuchang0719** [jobbole/translation-project#112]
1[.原文链接](https://medium.freecodecamp.org/how-to-become-a-git-expert-e7c38bf54826)
2.分类（见标签）：
3.推荐原因：讲了两个方法，修正 commits 和 rebase（不至于成为专家）。

-------

**Comment by bqlin** [comment]
认领翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
ok
