### ISSUE TITLE
GetStream.io: 为什么我们从Python迁移到了Go

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#124]
1.原文链接：  [GetStream.io: Why We Switched from Python to Go](https://codeburst.io/why-we-switched-from-python-to-go-60c8fd2cb9a9)
2.分类（见标签）：
3.推荐原因：比较了Python和Go的优缺点，给出了学习和迁移的相关资源

-------

**Comment by iython** [comment]
领取翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
好的
