### ISSUE TITLE
A comedy of errors. Debugging Java memory leaks.

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#13]
1.[原文链接](https://allegro.tech/2018/05/a-comedy-of-errors-debugging-java-memory-leaks.html)
2.分类（见标签）
3.推荐原因：有趣到debugging经历，问题与原因似乎毫不相关

-------
建议加入awesome bugs

**Comment by yizheWork** [comment]
认领翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
ok
