### ISSUE TITLE
cat命令的源码进化史

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#137]
1.原文链接：[source history of cat](https://twobithistory.org/2018/11/12/cat.html)
2.分类（见标签）：
3.推荐原因：计算机真的是一个日新月异，高速变化的领域吗？过去的知识难道真的会过时吗？至少，从某些程序的源码来看，似乎变化并没有我们想象的那么大

-------

**Comment by yiting007** [comment]
@hanxiaomax 认领翻译

**Comment by hanxiaomax** [comment]
ok
