### ISSUE TITLE
Mindful Machines Original Series, Big Data: Batch Storage (1)

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#14]
1.[原文链接](https://mindfulmachines.io/blog/2018/4/10/series-big-data-batch-storage)
2.分类（见标签）
3.推荐原因：
一个大数据存储技术的一个系列综述，涵盖比较广，选择的数据库也比较新，本文列举了多个数据存储产品和架构，并指出他们的特点，从摘要看，大概有5篇，涵盖批量存储，批处理，流处理，NoSQL 和架构，这是其中第一篇

-------

**Comment by white-rabit** [comment]
认领翻译
@hanxiaomax

**Comment by hanxiaomax** [comment]
ok，另外我已经把你加入到伯乐在线组织，需要你在邮箱链接里面确认一下
