### ISSUE TITLE
Mindful Machines Original Series, Big Data: Batch Processing (2)

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#15]
1.[原文链接](https://mindfulmachines.io/blog/2018/4/24/series-big-data-batch-processing)
2.分类（见标签）
3.推荐原因：
本文是大数据处理技术的一个系列综述，涵盖比较广，选择的数据库也比较新，本文列举了多个数据处理产品和特点，从摘要看，大概有5篇，涵盖批量存储，批处理，流处理，NoSQL 和架构，这是其中第二篇，批量处理

-------

**Comment by white-rabit** [comment]
申领翻译
@hanxiaomax
