### ISSUE TITLE
观念、学习方法、社会压力与工具——写给压力山大程序员的几则建议

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#151]
1.原文链接：[How to Feel Less Overwhelmed as a Developer](https://link.medium.com/HGLs9Zr0mU)
2.分类（见标签）：
3.推荐原因：
不论你的初学者，还是老司机，对于一个开发者来说，时刻都会感受到来自方方面面的压力，笔者从四个方面给出了行之有效的建议。

-------

**Comment by yuexiaofeng** [comment]
我来认领 :)

**Comment by hanxiaomax** [comment]
ok
