### ISSUE TITLE
【提升你的算法速度系列（2/4）】Numba使你的代码像C++一样快速

### ISSUE THREAD

**Issue by zxdefying** [jobbole/translation-project#162]
1.原文链接：https://towardsdatascience.com/speed-up-your-algorithms-part-2-numba-293e554c5cc1

2.分类（见标签）：【T-系列文章】【T-python】

3.推荐原因：我工作中使用python，numpy比较多，今天听同事提到numba可以加速运算，简单试了下，确实比较好用，而且使用也比较简单，对于做深度学习，数据处理的人，非常有必要了解这个神器。

-------

**Comment by hanxiaomax** [comment]
感谢。
另外如果认领这篇的话，请在评论里面回复一下，方便脚本统计`认领翻译`

**Comment by zxdefying** [comment]
认领翻译 @hanxiaomax
