### ISSUE TITLE
LINUX System Call Quick Reference

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#27]
1.[原文链接](https://www.developeralerts.com/linux-system-call-quick-reference/)
2.分类（见标签）
3.推荐原因：Linux系统调用速查手册

-------

**Comment by hanxiaomax** [comment]
@tangyouhua

**Comment by kele1997** [comment]
原文大概就是这个 [pdf 文档](http://www.cheat-sheets.org/saved-copy/Linux_Syscall_quickref.pdf),感觉翻译价值不大，不过已经可以闲暇打发时间，已经翻译了46条了:smile:,分配给我吧
