### ISSUE TITLE
9 Best Practices to Handle Exceptions in Java

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#29]
1.[原文链接](https://dzone.com/articles/9-best-practices-to-handle-exceptions-in-java)
2.分类（见标签）
3.推荐原因
异常处理是每个程序员都需要掌握的，这篇文章介绍了java异常处理的9个最佳实践，获得了100+👍

-------

**Comment by Marticles** [comment]
认领文章 @hanxiaomax

**Comment by hanxiaomax** [comment]
ok，6666

**Comment by Marticles** [comment]
哇，回复这么快。lol
