### ISSUE TITLE
计算机科学自学指南

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#30]
1.[原文链接](https://teachyourselfcs.com/)
2.分类（见标签）
3.推荐原因：
本文列举了一系列的cs自学资源，与一般的资源合集不同，本文帮你清楚的认识到，学什么，怎么学。
本文还是比较推荐的，内容不太多，针对计算机科学领域的几个重要话题，给出了最佳的参考书籍和视频，且针对自学者进行了优化，没有推荐特别艰深的书籍

-------

**Comment by nangua1995** [comment]
【认领翻译】

**Comment by nangua1995** [comment]
@hanxiaomax

**Comment by hanxiaomax** [comment]
@nangua1995 hi~老哥，我看你还没有fork过项目的repo，是遇到什么困难吗？比如说流程或者git操作不熟悉之类的，可以随时联系我。也可以在[这里](https://github.com/jobbole/trans-common-issue-tracker/issues)发issue询问

**Comment by hanxiaomax** [comment]
@nangua1995 请问这篇文章目前进展多少？已经一个月了。如果有什么困难可以反馈给我，如果不想翻译了，可以转给其他译者，这篇文章我认为价值还是比较大的

**Comment by nangua1995** [comment]
进行一半了…


| |
白鹤
邮箱：baihe9533@163.com
|

签名由 网易邮箱大师 定制

在2018年08月23日 21:17，Lingfeng_Ai 写道：

@nangua1995 请问这篇文章目前进展多少？已经一个月了。如果有什么困难可以反馈给我，如果不想翻译了，可以转给其他译者，这篇文章我认为价值还是比较大的

**Comment by hanxiaomax** [comment]
hi，这篇进展如何？

**Comment by nangua1995** [comment]
说来惭愧…已经翻译到最后的分布式系统了…尽量在下周把它传到GitHub上


| |
白鹤
邮箱：15522856437@163.com
|

签名由 网易邮箱大师 定制

在2018年10月06日 09:53，Lingfeng_Ai 写道：

hi，这篇进展如何？

**Comment by hanxiaomax** [comment]
加油↖(^ω^)↗

**Comment by nangua1995** [comment]
我想问一下这个要怎么提交呀？？因为平时工作的时候不怎么用GITHUB，所以对于这个不太熟悉。我从你的GitHub fork了代码到我的Res,然后提交的时候是如何pull request到你的仓库的呢？？

**Comment by hanxiaomax** [comment]
@nangua1995 你可以先看一下我录制的[视频教程](http://www.bilibili.com/video/av27999596/) ，如果还不明白，我明天详细给你讲～另外咱们项目的wiki里面也有[文字介绍](https://github.com/jobbole/translation-project/wiki)

简单来讲就是，在你先把你的修改，commit到你自己的repo，然后在你的repo里面点new pull request，然后选择目标repo是jobbole的trans分支，源是你自己的分支。

**Comment by nangua1995** [comment]
酱紫…OK 我明天试一下


| |
白鹤
邮箱：baihe9533@163.com
|

签名由 网易邮箱大师 定制

在2018年10月23日 22:44，Lingfeng_Ai 写道：

@nangua1995 你可以先看一下我录制的视频教程 ，如果还不明白，我明天详细给你讲～另外咱们项目的wiki里面也有文字介绍

简单来讲就是，在你先把你的修改，commit到你自己的repo，然后在你的repo里面点new pull request，然后选择目标repo是jobbole的trans分支，源是你自己的分支。

**Comment by hanxiaomax** [comment]
这篇抽空提交一下吧 @nangua1995

**Comment by nangua1995** [comment]
sorry 好的👌


| |
白鹤
邮箱：baihe9533@163.com
|

签名由 网易邮箱大师 定制

在2018年11月11日 22:05，Lingfeng_Ai 写道：

这篇抽空提交一下吧 @nangua1995
