### ISSUE TITLE
3 Things Every Java Developer Should Stop Doing

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#31]
1.[原文链接](https://dzone.com/articles/3-things-every-java-developer-should-stop-doing)
2.分类（见标签）
3.推荐原因

-------

**Comment by yizheWork** [comment]
认领翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
太高产了，老哥

**Comment by hanxiaomax** [comment]
@yizheWork 老哥，这篇进展如何？

**Comment by yizheWork** [comment]
最近项目比较忙，我周末搞完吧

**Comment by hanxiaomax** [comment]
好滴不急，我就问问

**Comment by hanxiaomax** [comment]
没关系。翻译了大概有多少能？超过一半了吗？你觉得有么有价值翻译完？

**Comment by yizheWork** [comment]
1/3了吧，有点没信心。本来一周一篇，中间有点事把节奏断了，现在有点迷。

**Comment by hanxiaomax** [comment]
那算了，我先把文章恢复成TODO，你可以认领其他的，或者休息休息

**Comment by AtlantisLee** [comment]
认领校对 @hanxiaomax

**Comment by hanxiaomax** [comment]
好的
@AtlantisLee
