### ISSUE TITLE
HTTPS explained with carrier pigeons

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#32]
1.[原文链接](https://medium.freecodecamp.org/https-explained-with-carrier-pigeons-7029d2193351)
2.分类（见标签）
3.推荐原因
通过信鸽来解释HTTPS，有趣易懂，但是没什么图片。原文有韩文和葡语版本，可以翻译完之后请作者加上我们的中文版

-------

**Comment by iython** [comment]
认领翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
好滴，辛苦
