### ISSUE TITLE
Non-obvious possibilities of python syntax 鲜为人知的python语法

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#35]
1.[原文链接](https://medium.com/@chipiga86/non-obvious-possibilities-of-python-syntax-a95a7210aaaf)
2.分类（见标签）
3.推荐原因
鲜为人知的python语法

-------

**Comment by kele1997** [comment]
认领翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
ok
