### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by shiminli-cs** [jobbole/translation-project#41]
*标题请填写：译者申请*

1. 擅长领域：算法
2. 在职/在校：助理教授
3. 每周的空闲时间：1天
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：無
6. 从何处了解到伯乐在线翻译组/为何加入：讀過不少翻譯的好文章，很有興趣貢獻自己的力量
7. 简单自我介绍：CS專業的本科教師，博士研究方向是算法，側重計算幾何方向。目前在美國明尼蘇達州維諾納市。教師空閒時間比較多，沒課的時候基本沒事。想利用空閒時間關注計算機行業發展前沿。
網址：https://sites.google.com/a/aggiemail.usu.edu/shiminli/home

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
试译已经发送

**Comment by hanxiaomax** [comment]
试译通过，欢迎加入~
