### ISSUE TITLE
泪流满面的 11 个 Git 面试题

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#52]
1.[原文链接](https://dev.to/aershov24/11-painful-git-interview-questions-you-will-cry-on-1n2g)
2.分类（见标签）
3.推荐原因:11个面试中会问到的Git问题，问到你泪流满面

-------

**Comment by bqlin** [comment]
认领翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
ok

**Comment by hanxiaomax** [comment]
@huanglimin 可以发布了
