### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by rnmb** [jobbole/translation-project#55]
*标题请填写：译者申请*
*lable请选择：M-Apply*

1. 擅长领域：java 分布式 、并发、mysql redis mq 等
2. 在职/在校：在职
3. 每周的空闲时间： 碎片时间
4. 能否科学上网：无法保证，工作网络状态一般，时长无法连接
5. 有无翻译经验（如果有，欢迎附上链接）：无
6. 从何处了解到伯乐在线翻译组/为何加入：在importnew 上看到翻译的文章，感觉内容不错
7. 简单自我介绍：
非常喜欢开发，但是在平常的开发中，感觉接触的还是不够多，希望能通过翻译学习到更多的东西，也能学习英语(●'◡'●)

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
试译已发送
