### ISSUE TITLE
为什么 Python 如此这般的慢？

### ISSUE THREAD

**Issue by liuchang0719** [jobbole/translation-project#57]
1[.原文链接](https://hackernoon.com/why-is-python-so-slow-e5074b6fe55b)
2.Python
3.常见的面试题储备。

-------

**Comment by brightsunp** [comment]
@hanxiaomax 

Hello，我本打算认领这篇文章，但是查资料的过程中，发现已经有一篇类似的翻译：
[热度碾压 Java、C#、C++的 Python，为什么速度那么慢？](https://yq.aliyun.com/articles/620703?utm_content=m_1000010454)

你看这个 issue 还要走下去吗？

**Comment by hanxiaomax** [comment]
@brightsunp 如果你有兴趣，仍然可以翻译。当然也可以选择其他的。不过，其实这个话题也比较老生常谈了，我建议还是选择其他文章吧

**Comment by brightsunp** [comment]
@hanxiaomax 仔细看了下，链接里对应的正是这篇。

> 原文发布时间为：2018-07-30
本文作者：Anthony Shaw 

那还是选择其他的好了。

**Comment by hanxiaomax** [comment]
重复文章，关闭
