### ISSUE TITLE
正则表达式的隐藏陷阱，你都了解么？

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#60]
1.[原文链接](https://www.tutorialdocs.com/article/regex-trap.html)
2.分类（见标签）
3.推荐原因：正则表达式里面的隐藏陷阱

-------

**Comment by white-rabit** [comment]
认领翻译

**Comment by hanxiaomax** [comment]
#15 这篇完工了吗？
@white-rabit
