### ISSUE TITLE
编辑器之神 Vim 是从哪里来的？

### ISSUE THREAD

**Issue by huanglimin** [jobbole/translation-project#64]
Where Vim Came From
链接：https://twobithistory.org/2018/08/05/where-vim-came-from.html
推荐原因：告知你 Vim 是如何诞生的

-------

**Comment by Nana-Lv** [comment]
认领翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
@Nana-Lv 好滴～

**Comment by hanxiaomax** [comment]
@Nana-Lv 哈喽，这篇进展如何呢？

**Comment by Nana-Lv** [comment]
抱歉 目前翻译完了 处在检查阶段

**Comment by hanxiaomax** [comment]
加油  ✺◟(∗❛ัᴗ❛ั∗)◞✺
