### ISSUE TITLE
常被问到的10个Java面试题

### ISSUE THREAD

**Issue by tangyouhua** [jobbole/translation-project#81]
1.原文链接：https://dzone.com/articles/top-10-java-interview-questions-that-i-recently-fa
2.分类（见标签）：
3.推荐原因：文中列出了作者面试中遇到的10个常见Java面试题，并给出了分析和解答。

-------

**Comment by AtlantisLee** [comment]
认领翻译
@hanxiaomax

**Comment by hanxiaomax** [comment]
好的
