### ISSUE TITLE
香农：真正的天才是如何解决问题的

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#83]
1.原文链接：[Claude Shannon: How a Genius Solves Problems](https://medium.com/personal-growth/claude-shannon-how-a-real-genius-solves-problems-15b434aeb2b6)
2.分类（见标签）：
3.推荐原因：medium 15k+👍，如何分析解决问题

-------

**Comment by HuihuangZhang** [comment]
【认领翻译】 @hanxiaomax
