### ISSUE TITLE
果壳中的软件架构

### ISSUE THREAD

**Issue by hanxiaomax** [jobbole/translation-project#84]
1.原文链接：[10 Common Software Architectural Patterns in a nutshell](https://towardsdatascience.com/10-common-software-architectural-patterns-in-a-nutshell-a0b47a1e9013?source=linkShare-2f2dd2d6cf47-1536124134)
2.分类（见标签）：软件架构
3.推荐原因：
常见的十种软件架构

-------

**Comment by HuihuangZhang** [comment]
认领翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
ok
