### ISSUE TITLE
写给自己的软件工程笔记

### ISSUE THREAD

**Issue by liuchang0719** [jobbole/translation-project#86]
1.[原文链接](https://medium.com/@francois.chollet/notes-to-myself-on-software-engineering-c890f16f4e4d)
2.分类（见标签）
3.推荐原因：Keras 的开发者 François Chollet 整理的笔记。关于软件开发流程、API 设计、职场等方面的思考。

-------

**Comment by jessie-alpha** [comment]
认领翻译
@hanxiaomax

**Comment by hanxiaomax** [comment]
ok，您注意查收一下团队邀请，在绑定GitHub的邮箱里面
