### ISSUE TITLE
用 Quartz 运行一个 Spring Batch Job

### ISSUE THREAD

**Issue by tangyouhua** [jobbole/translation-project#89]
1.原文链接：https://dzone.com/articles/spring-batch-with-quartz
2.分类（见标签）：
3.推荐原因：介绍了如何用 Quartz 调度器运行一个 Spring Batch Job

-------

**Comment by youngLake** [comment]
@hanxiaomax  认领翻译

**Comment by hanxiaomax** [comment]
ok
