### ISSUE TITLE
使用 Thread Pool 不当引发的死锁

### ISSUE THREAD

**Issue by tangyouhua** [jobbole/translation-project#90]
1.原文链接：https://dzone.com/articles/thread-pool-self-induced-deadlocks
2.分类（见标签）：
3.推荐原因：在一个单线程中，如果 Thread Pool 使用不当也会引发死锁。文章分析了背后的原因，并给出了如何避免死锁的建议。

-------

**Comment by Snowhere** [comment]
认领翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
OK

**Comment by tangyouhua** [comment]
已发布，[http://www.importnew.com/30277.html](http://www.importnew.com/30277.html)
