### ISSUE TITLE
Oracle JDK 构建 vs OpenJDK 构建：理解二者的区别

### ISSUE THREAD

**Issue by tangyouhua** [jobbole/translation-project#91]
1.原文链接：https://jaxenter.com/oracle-jdk-builds-openjdk-builds-difference-149318.html
2.分类（见标签）：
3.推荐原因：介绍了 Oracle JDK 构建与 OpenJDK 构建程序之间的区别。

-------

**Comment by youngLake** [comment]
认领翻译
@hanxiaomax

**Comment by hanxiaomax** [comment]
ok

**Comment by hanxiaomax** [comment]
@youngLake 请查收一下团队邀请链接（邮箱）
