### ISSUE TITLE
使用 IntelliJ 调试 Java Streams

### ISSUE THREAD

**Issue by tangyouhua** [jobbole/translation-project#93]
1.原文链接：https://www.javacodegeeks.com/2018/09/debugging-java-streams-with-intellij.html
2.分类（见标签）：
3.推荐原因：本文介绍了如何使用 Stream debugger 配合 Speedment 工具调试 Java Streams。

-------

**Comment by Snowhere** [comment]
认领翻译 @hanxiaomax

**Comment by hanxiaomax** [comment]
好的
